import type { Article, Category } from './types';
import { Code2, UtensilsCrossed, Globe, Briefcase, Smile } from 'lucide-react';

export const CATEGORIES: Category[] = [
  { name: 'Tech', slug: 'tech', icon: Code2 },
  { name: 'Food', slug: 'food', icon: UtensilsCrossed },
  { name: 'World', slug: 'world', icon: Globe },
  { name: 'Business', slug: 'business', icon: Briefcase },
  { name: 'Lifestyle', slug: 'lifestyle', icon: Smile },
];

export const ARTICLES: Article[] = [
  {
    slug: 'ai-in-2024',
    title: 'The Future of AI: Trends to Watch in 2024',
    description: 'A deep dive into the upcoming trends in artificial intelligence and machine learning.',
    content: 'The year 2024 is poised to be a landmark year for Artificial Intelligence. From advancements in large language models to the proliferation of AI in everyday applications, the landscape is rapidly evolving. This article explores the key trends, potential breakthroughs, and ethical considerations that will shape the future of AI. We will discuss the impact on industries like healthcare, finance, and entertainment, and what it means for society as a whole. Join us as we unpack the exciting and complex world of AI in the coming year.',
    author: 'Jane Doe',
    publishedAt: '2024-07-15',
    featuredImage: '/images/featured-image.png',
    category: 'tech',
    tags: ['AI', 'Machine Learning', 'Tech Trends'],
    featured: true,
  },
  {
    slug: 'quantum-computing-breakthrough',
    title: 'Quantum Computing: A New Era of Computation',
    description: 'Exploring the latest breakthroughs in quantum computing and its potential to revolutionize technology.',
    content: 'Quantum computing is no longer a theoretical concept. Recent breakthroughs have brought us closer to a new era of computation that could solve problems currently intractable for classical computers. This article delves into the principles of quantum mechanics that power these machines, the challenges in building stable quantum computers, and the potential applications in fields like medicine, materials science, and cryptography. We are standing on the precipice of a technological revolution, and understanding quantum computing is key to navigating the future.',
    author: 'John Smith',
    publishedAt: '2024-07-10',
    featuredImage: '/images/featured-image.png',
    category: 'tech',
    tags: ['Quantum Computing', 'Technology', 'Science'],
  },
  {
    slug: 'sustainable-gastronomy',
    title: 'The Rise of Sustainable Gastronomy',
    description: 'How chefs and restaurants are embracing sustainability to create a better food future.',
    content: 'Sustainability is the new buzzword in the culinary world. From farm-to-table sourcing and zero-waste kitchens to plant-based menus, chefs are redefining what it means to eat well. This piece explores the movement of sustainable gastronomy, highlighting innovative restaurants and culinary pioneers who are making a difference. We look at the environmental impact of our food choices and how conscious cooking can lead to a healthier planet and more delicious meals. Discover how your next dinner out could be part of a global solution.',
    author: 'Emily White',
    publishedAt: '2024-07-12',
    featuredImage: '/images/featured-image.png',
    category: 'food',
    tags: ['Sustainability', 'Food', 'Dining'],
    featured: true,
  },
  {
    slug: 'the-perfect-sourdough',
    title: 'Baking the Perfect Sourdough at Home',
    description: 'A step-by-step guide to mastering the art and science of sourdough bread.',
    content: 'The allure of a warm, crusty loaf of homemade sourdough is undeniable. What was once a pandemic hobby has become a passionate pursuit for many home bakers. This guide demystifies the process, from creating and maintaining a healthy starter to achieving the perfect oven spring. With detailed instructions, troubleshooting tips, and a little bit of science, you\'ll be on your way to baking bread that rivals your favorite artisan bakery. All you need is flour, water, salt, and patience.',
    author: 'Michael Brown',
    publishedAt: '2024-07-08',
    featuredImage: '/images/featured-image.png',
    category: 'food',
    tags: ['Baking', 'Cooking', 'DIY'],
  },
  {
    slug: 'global-economic-outlook',
    title: 'Navigating the Global Economic Outlook for H2 2024',
    description: 'An analysis of the key economic factors shaping markets around the world.',
    content: 'As we enter the second half of 2024, the global economy stands at a crossroads. This article provides a comprehensive analysis of the major economic indicators, geopolitical events, and policy decisions influencing financial markets. We examine inflation rates, interest rate policies from central banks, and trade relations between key global players. For investors and business leaders, understanding these complex dynamics is crucial for making informed decisions in a volatile environment.',
    author: 'Sarah Green',
    publishedAt: '2024-07-14',
    featuredImage: '/images/featured-image.png',
    category: 'business',
    tags: ['Economics', 'Finance', 'Markets'],
  },
  {
    slug: 'the-four-day-work-week',
    title: 'The Four-Day Work Week: Fad or Future?',
    description: 'Companies are experimenting with a shorter work week. We look at the pros, cons, and results.',
    content: 'The traditional 9-to-5, five-day work week is being challenged. A growing number of companies are trialing a four-day work week, and the results are promising. Proponents cite increased productivity, improved employee well-being, and a smaller carbon footprint. However, critics raise concerns about implementation challenges and suitability for all industries. This article examines case studies from around the world, weighs the evidence, and asks the question: Is the four-day work week the future of work?',
    author: 'David Chen',
    publishedAt: '2024-07-05',
    featuredImage: '/images/featured-image.png',
    category: 'business',
    tags: ['Future of Work', 'Productivity', 'Corporate Culture'],
  },
  {
    slug: 'cultural-festivals-around-the-world',
    title: 'A Journey Through the World\'s Most Vibrant Cultural Festivals',
    description: 'From Rio\'s Carnival to India\'s Holi, a celebration of global traditions and human connection.',
    content: 'Festivals are the heartbeat of culture. They are a time for celebration, reflection, and community. This photo-essay takes you on a visual journey to some of the world\'s most spectacular cultural events. Experience the color and energy of Holi, the dazzling parades of Carnival, the serene beauty of the Lantern Festival in Thailand, and more. Through stunning photography and firsthand accounts, we explore the history and significance of these traditions and celebrate the universal human desire for connection and joy.',
    author: 'Maria Garcia',
    publishedAt: '2024-07-11',
    featuredImage: '/images/featured-image.png',
    category: 'world',
    tags: ['Travel', 'Culture', 'Festivals'],
  },
  {
    slug: 'digital-nomad-visas',
    title: 'The Rise of Digital Nomad Visas',
    description: 'How countries are adapting to the new reality of remote work to attract global talent.',
    content: 'The remote work revolution has given rise to a new class of professional: the digital nomad. In response, dozens of countries have launched special visas to attract these location-independent workers. This article provides a guide to the best digital nomad visas available in 2024, covering requirements, costs, and the lifestyle offered in each destination. From the beaches of the Caribbean to the historic cities of Europe, we explore how this trend is reshaping tourism and immigration.',
    author: 'Ben Carter',
    publishedAt: '2024-07-02',
    featuredImage: '/images/featured-image.png',
    category: 'world',
    tags: ['Remote Work', 'Travel', 'Visas'],
  },
  {
    slug: 'mindfulness-in-the-digital-age',
    title: 'Finding Calm: Mindfulness in the Digital Age',
    description: 'Practical tips for cultivating mindfulness and reducing stress in our hyper-connected world.',
    content: 'In a world of constant notifications and information overload, finding moments of peace can feel impossible. Mindfulness offers a powerful antidote. This article explores the science behind mindfulness and provides practical, accessible techniques to incorporate it into your daily life. From simple breathing exercises to digital detox strategies, learn how to reduce stress, improve focus, and cultivate a greater sense of well-being, even when you\'re tethered to your devices.',
    author: 'Dr. Evelyn Reed',
    publishedAt: '2024-07-09',
    featuredImage: '/images/featured-image.png',
    category: 'lifestyle',
    tags: ['Mindfulness', 'Wellness', 'Mental Health'],
  },
  {
    slug: 'the-art-of-minimalism',
    title: 'The Art of Minimalism: More Than Just Less Stuff',
    description: 'Discover how minimalism can lead to a more intentional and fulfilling life.',
    content: 'Minimalism is often misunderstood as simply owning fewer possessions. In reality, it\'s a mindset focused on intentionality. By clearing away the clutter—physical, mental, and digital—we can make room for what truly matters. This article delves into the philosophy of minimalism, offering practical advice on how to declutter your life and focus your time and energy on your values and passions. It\'s not about deprivation; it\'s about gaining freedom.',
    author: 'Leo Kim',
    publishedAt: '2024-06-30',
    featuredImage: '/images/featured-image.png',
    category: 'lifestyle',
    tags: ['Minimalism', 'Self-Improvement', 'Philosophy'],
  },
];
